spring.application.name=Lab11

# ===============================
# THYMELEAF (optional tweak)
# ===============================
spring.thymeleaf.cache=false

# ===============================
# MYSQL DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/nutsshop_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Show SQL in console (great for teaching)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
